version: '3.4'

services:
  mockesu.web:
    image: ${DOCKER_REGISTRY-}mockesuweb
    build:
      context: .
      dockerfile: MockEsu.Web/Dockerfile
    ports:
      - "5150:5150"
      - "7150:7150"